# ------------------------------------------------------------------------ INFO
# [/ael-files/ael-packages.toml]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2025-12-28 18:15:12 UTC
# updated       : 2026-01-03 03:02:03 UTC
# description   : Packages

[bash]
url           = "https://www.gnu.org/software/bash/bash.html"
description   = "The GNU Bourne Again shell."
repository    = "core"
included_app  = [
                "/usr/bin/bash",
                "/usr/bin/bashbug",
                "/usr/bin/rbash",
                "/usr/bin/sh",
                ]

[coreutils] # {{{
url           = "https://www.gnu.org/software/coreutils/"
description   = "The basic file, shell and text manipulation utilities of the GNU operating system."
repository    = "core"
included_app  = [
                "/usr/bin/[",
                "/usr/bin/b2sum",
                "/usr/bin/base32",
                "/usr/bin/base64",
                "/usr/bin/basename",
                "/usr/bin/basenc",
                "/usr/bin/cat",
                "/usr/bin/chgrp",
                "/usr/bin/chmod",
                "/usr/bin/chown",
                "/usr/bin/chroot",
                "/usr/bin/cksum",
                "/usr/bin/comm",
                "/usr/bin/cp",
                "/usr/bin/csplit",
                "/usr/bin/cut",
                "/usr/bin/date",
                "/usr/bin/dd",
                "/usr/bin/df",
                "/usr/bin/dir",
                "/usr/bin/dircolors",
                "/usr/bin/dirname",
                "/usr/bin/du",
                "/usr/bin/echo",
                "/usr/bin/env",
                "/usr/bin/expand",
                "/usr/bin/expr",
                "/usr/bin/factor",
                "/usr/bin/false",
                "/usr/bin/fmt",
                "/usr/bin/fold",
                "/usr/bin/groups",
                "/usr/bin/head",
                "/usr/bin/hostid",
                "/usr/bin/id",
                "/usr/bin/install",
                "/usr/bin/join",
                "/usr/bin/link",
                "/usr/bin/ln",
                "/usr/bin/logname",
                "/usr/bin/ls",
                "/usr/bin/md5sum",
                "/usr/bin/mkdir",
                "/usr/bin/mkfifo",
                "/usr/bin/mknod",
                "/usr/bin/mktemp",
                "/usr/bin/mv",
                "/usr/bin/nice",
                "/usr/bin/nl",
                "/usr/bin/nohup",
                "/usr/bin/nproc",
                "/usr/bin/numfmt",
                "/usr/bin/od",
                "/usr/bin/paste",
                "/usr/bin/pathchk",
                "/usr/bin/pinky",
                "/usr/bin/pr",
                "/usr/bin/printenv",
                "/usr/bin/printf",
                "/usr/bin/ptx",
                "/usr/bin/pwd",
                "/usr/bin/readlink",
                "/usr/bin/realpath",
                "/usr/bin/rm",
                "/usr/bin/rmdir",
                "/usr/bin/seq",
                "/usr/bin/sha1sum",
                "/usr/bin/sha224sum",
                "/usr/bin/sha256sum",
                "/usr/bin/sha384sum",
                "/usr/bin/sha512sum",
                "/usr/bin/shred",
                "/usr/bin/shuf",
                "/usr/bin/sleep",
                "/usr/bin/sort",
                "/usr/bin/split",
                "/usr/bin/stat",
                "/usr/bin/stdbuf",
                "/usr/bin/stty",
                "/usr/bin/sum",
                "/usr/bin/sync",
                "/usr/bin/tac",
                "/usr/bin/tail",
                "/usr/bin/tee",
                "/usr/bin/test",
                "/usr/bin/timeout",
                "/usr/bin/touch",
                "/usr/bin/tr",
                "/usr/bin/true",
                "/usr/bin/truncate",
                "/usr/bin/tsort",
                "/usr/bin/tty",
                "/usr/bin/uname",
                "/usr/bin/unexpand",
                "/usr/bin/uniq",
                "/usr/bin/unlink",
                "/usr/bin/users",
                "/usr/bin/vdir",
                "/usr/bin/wc",
                "/usr/bin/who",
                "/usr/bin/whoami",
                "/usr/bin/yes"
                ] # }}}

[ffmpeg]
url           = "https://ffmpeg.org"
description   = "Complete solution to record, convert and stream audio and video."
repository    = "extra"
included_app  = [
                "/usr/bin/ffmpeg",
                "/usr/bin/ffprobe",
                "/usr/bin/qt-faststart"
                ]

[findutils]
url           = "https://www.gnu.org/software/findutils/"
description   = "GNU utilities to locate files."
repository    = "core"
included_app  = [
                "/usr/bin/find",
                "/usr/bin/xargs"
                ]

[grep]
url           = "https://www.gnu.org/software/grep/"
description   = "A string search utility."
repository    = "core"
included_app  = [
                "/usr/bin/egrep",
                "/usr/bin/fgrep",
                "/usr/bin/grep"
                ]

[grc]
url           = "https://github.com/garabik/grc"
description   = "Yet another colouriser for beautifying your logfiles or output of commands."
repository    = "extra"
included_app  = [
                "/usr/bin/grc",
                "/usr/bin/grcat"
                ]

[nmap]
url           = "https://nmap.org/"
description   = "Utility for network discovery and security auditing."
repository    = "extra"
included_app  = [
                "/usr/bin/ncat",
                "/usr/bin/nmap",
                "/usr/bin/nping"
                ]

[python]
url           = "https://www.python.org/"
description   = "The Python programming language"
repository    = "core"
included_app  = [
                "/usr/bin/idle",
                "/usr/bin/idle3",
                "/usr/bin/idle3.13",
                "/usr/bin/pydoc",
                "/usr/bin/pydoc3",
                "/usr/bin/pydoc3.13",
                "/usr/bin/python",
                "/usr/bin/python-config",
                "/usr/bin/python3",
                "/usr/bin/python3-config",
                "/usr/bin/python3.13",
                "/usr/bin/python3.13-config"
                ]

[rustscan]
url           = "https://github.com/rustscan/RustScan"
description   = "A modern port scanner."
repository    = "extra"
included_app  = [
                "/usr/bin/rustscan"
                ]

[sudo]
url           = "https://www.sudo.ws/sudo/"
description   = "Give certain users the ability to run some commands as root."
repository    = "core"
included_app  = [
                "/usr/bin/cvtsudoers",
                "/usr/bin/sudo",
                "/usr/bin/sudo_logsrvd",
                "/usr/bin/sudo_sendlog",
                "/usr/bin/sudoedit",
                "/usr/bin/sudoreplay",
                "/usr/bin/visudo"
                ]

[tmux]
url             = "https://github.com/tmux/tmux/wiki"
description     = "Terminal multiplexer."
repository      = "extra"
included_app  = [
                "/usr/bin/tmux"
                ]

[vim]
url           = "https://www.vim.org"
description   = "Vi Improved, a highly configurable, improved version of the vi text editor."
repository    = "extra"
included_app  = [
                "/usr/bin/rview",
                "/usr/bin/rvim",
                "/usr/bin/vim",
                "/usr/bin/vimdiff",
                "/usr/bin/vimtutor",
                "/usr/bin/xxd"
                ]

[yt-dlp]
url           = "https://github.com/yt-dlp/yt-dlp"
description   = "A youtube-dl fork with additional features and fixes."
repository    = "extra"
included_app  = [
                "/usr/bin/yt-dlp"
                ]

# vim: foldmethod=marker
